### PR TITLE
fix(Inputs Module): Improve the size for internal circle in radio inputs

### PR DESCRIPTION
**Pull request by zetogk**
The icons from 'FontAwesome' have been replaced with custom SVG icons (Based on 'FontAwesome') with the objective of match the final result with guidelines of Zeplin.

### CODE REVIEW

**Comment by zetogk** [comment]
@CristinaSolana the styles for checkboxes and radio buttons are ready.

**Comment by CristinaSolana** [comment]
@zetogk In this PR, the background color of the checkbox was changed from blue to white and checkmark color was changed from blue to white. I'm going to go ahead and wrap up this module since we have page layouts that need to be worked on.

**Comment by zetogk** [comment]
@CristinaSolana The icon already has been changed.

**Comment by zetogk** [comment]
@CristinaSolana Do you think that this is well or missing something?

**Pull request closed without merging**
