### PR TITLE
Fix/after nov 27

### PR DESCRIPTION
**Pull request by itsDiwaker**
**List of issues fixed:**

ITA-306
ITA-356
ITA-380
ITA-382
ITA-383
ITA-384
#401 
#402 

**Non ticket fixes/bugs:**

- Add validation to prompt user to save shipping address if it has been changed since the last save. 
- Implement cross step validations. 
- Fix CC wrong left amount calculation bug. 
- Fix MONGO db limitation issue with client.attributes data same as profile edit page.

### CODE REVIEW

**Comment by CristinaSolana** [comment]
@itsDiwaker Cannot properly test ITA-306 because of an unrelated error. When deleting an item from cart, although the item is deleted, it still appears in the cart because of the error below. I need to be able to test that when an item is removed from cart and cart is empty, that checkout button is disabled.

screen shot 2017-12-08 at 4 30 23 pm

**Comment by CristinaSolana** [comment]
When addCash is off and PAG is enabled, the credit card form shows. There should be no cc form is addCash is false

screen shot 2017-12-08 at 4 41 53 pm

screen shot 2017-12-08 at 4 41 43 pm

**Comment by CristinaSolana** [comment]
Still seeing websiteSettings.tax.taxExempt on that cart page - it is for the breadcrumbs, so you can use whatever logic you use to show the form to show the breadcrumbs as well. Assuming it will be easier to give a class to the list items in question (which include separators) and just use JS to show/hide instead of the Liquid conditional.

**Comment by itsDiwaker** [comment]
When point conversion set to 1.5. 
5 - 100 becomes 4 - 101
20 - 200 becomes 19 - 200

It will result in 4 to 101 range in the applied filter. 

It's due to the fact that while reading money value from url, I am using `floor` to fill from input field and `ceil` to fill to input field to make sure product's are searched properly.

Moreover, 5-100 actually results in a search criteria below:
screen shot 2017-12-09 at 3 56 44 am

And 20-200 search criteria becomes:
screen shot 2017-12-09 at 3 56 29 am

This may leave out few items from search result, may be in rare cases but there's a possibility.

**Comment by CristinaSolana** [comment]
@itsDiwaker I found the specific use case that causes the cc form to show on PAG enabled with addCash off. When the item points in the cart exceeds the participants points.

**Comment by CristinaSolana** [comment]
@itsDiwaker I will be looking at the points issue to figure out a solution later today. :)

**Comment by itsDiwaker** [comment]
> @itsDiwaker I found the specific use case that causes the cc form to show on PAG enabled with 
> addCash off. When the item points in the cart exceeds the participants points.

Hey @CristinaSolana  
This issue has been fixed, however it's pointing to another issue that we are able to add products to cart having prices greater than customer's available points when the addCash setting is OFF. Ideally I should not be able to add such products to cart or addCash setting should not be OFF.

**Comment by CristinaSolana** [comment]
@itsDiwaker The TIN masking looks good, but is a bit buggy when deleting some characters... dropping you a video

**Comment by CristinaSolana** [comment]
@itsDiwaker point range with point conversion is working well with the exception of a 0 being in the starting field return NaN. When the number is a 0, we should leave it as is instead of dividing it - not sure if that is the issue just making a best guess.

screen shot 2017-12-12 at 2 57 55 pm

**Comment by itsDiwaker** [comment]
@CristinaSolana I have covered all 3 feedbacks. Let me know if you still see any issues.

**Comment by CristinaSolana** [comment]
@itsDiwaker this is purely aesthetic, but can we put the alert inside the container so that it is the same width as the content below it. You can use the margin-bottom class on it to keep it from butting up against the content. :)

screen shot 2017-12-14 at 8 45 24 am

**Comment by itsDiwaker** [comment]
sure, tomorrow fine?

**Comment by CristinaSolana** [comment]
@itsDiwaker a few little details to fix:

After removing item from cart so that it does not exceed the participant's points

- the warning messages remain
- order summary total is wrong
- on both cart order summary and cart popover points are displaying with decimal, should be integer

screen shot 2017-12-14 at 8 56 24 am

**Pull request merged**
