### PR TITLE
feat(Checkout Billing Step): Add ability to save seperate billing.

### PR DESCRIPTION
**Pull request by itsDiwaker**
**Improvements:**

- Seperate billing and shipping addresses. 
- Different default billing & shipping addresses. 
- Same as billing functionality improvements. 
- Progress section update for shipping improved. 
- Billing address save to customer as default billing ability. 
- Address format for shippng progress review.

#339

### CODE REVIEW

**Comment by CristinaSolana** [comment]
@itsDiwaker, some issues with the address validation modal:
1. Too much space under titles: "Save the correct address" and "or Select a recommended address". Make bottom margins smaller
2. Change modal title to "Choose an address" and remove margin from top
3. Make "or Select a recommended address" smaller font size than the modal title
4. Address blocks under "or Select a recommended address" not aligned to begin same as the use my address
5. Addresses under "or Select a recommended address" have the city, state and zip twice (seems like it is added as line 2 of the address

**Comment by itsDiwaker** [comment]
_Fixes TODO:_
- `showAddressConfirmationModel`: trigger click to update data attribute when some address is already selected.

- `country` field is missing from shipping & billing form.

**Comment by CristinaSolana** [comment]
@itsDiwaker I went ahead and fixed #1-3 of the above issues I reported.

**Comment by itsDiwaker** [comment]
oops, I fixed it too..

**Pull request merged**
