### PR TITLE
Feature/checkout shipping

### PR DESCRIPTION
**Pull request by itsDiwaker**
No Payment Only shipping address Mode.
Check cart page for any -ve effects.

### CODE REVIEW

**Comment by itsDiwaker** [comment]
Hi @CristinaSolana, it's up for your review. Let me know if you find anything missing.

**Comment by CristinaSolana** [comment]
@itsDiwaker These parts seems to be missing. Am I right?

screen shot 2017-09-01 at 7 43 13 am

screen shot 2017-09-01 at 7 42 57 am

**Comment by CristinaSolana** [comment]
Some fixes:

1. Additional Payment Needed alert should show on both mobile and desktop, I know there is not example.
screen shot 2017-09-01 at 7 42 30 am

2. Alignment is off. Looks like you are missing a grid-container class on a parent div somewhere
screen shot 2017-09-01 at 7 38 37 am
screen shot 2017-09-01 at 7 38 37 am 2

**Comment by itsDiwaker** [comment]
@CristinaSolana,

1. That additional payment notice is there on mobile screen, attaching a screenshot:
screen shot 2017-09-01 at 6 56 06 pm

2. Grid container has been added.

**Pull request merged**
