### PR TITLE
Fix/after nov 27

### PR DESCRIPTION
**Pull request by itsDiwaker**

### CODE REVIEW

**Comment by CristinaSolana** [comment]
Remove one of the plus signs...
screen shot 2017-12-27 at 9 04 11 am

**Comment by CristinaSolana** [comment]
When attempting to save the tax address, the business name is set to blank and does not allow save.
https://www.dropbox.com/s/edtizohulf286ug/business-name-blank-on-save.mov?dl=0

Site Settings: All tax fields turned on, addCash on, PAG mode disabled

**Comment by CristinaSolana** [comment]
In both PAG enabled and disabled modes, still seeing cart drop down as it was before (RE: ITA-410)

screen shot 2017-12-27 at 9 25 15 am

**Comment by CristinaSolana** [comment]
Billing address no longer populated although the same as shipping is checked

screen shot 2017-12-27 at 9 39 08 am

**Comment by itsDiwaker** [comment]
> When attempting to save the tax address, the business name is set to blank and does not allow > save.
> https://www.dropbox.com/s/edtizohulf286ug/business-name-blank-on-save.mov?dl=0

> Site Settings: All tax fields turned on, addCash on, PAG mode disabled

**Reply:** I'll check for issues reported here once you merge pull request: #428. As I believe these have been fixed in that pull request.

**Pull request merged**
