### PR TITLE
Feat/product variant v2

### PR DESCRIPTION
**Pull request by CristinaSolana**

### CODE REVIEW

**Comment by CristinaSolana** [comment]
@itsDiwaker let's use this branch for getting #240 done. What I did here is show the sku data initially if it is not a product.subtype of variants or group-variant since there will only be one item in the array.

**Comment by itsDiwaker** [comment]
Below sections are being updated based on the final selection:

- Product Price
- `data-product-sku` to add to wishlist
- Product Description tab
- Product Specification tab:
    - Sku
    - Dimensions
    - Documents

**Comment by itsDiwaker** [comment]
I would have to test it with products having arbitrary number of selections( one & more than two attributes which can be mix of swatches/dropdowns) to assure stability of the code. 

If you can point me to few more products to test with? Otherwise I'll try to create few for myself.

**Comment by CristinaSolana** [comment]
@itsDiwaker I mentioned before that everything should be a dropdown. No swatches or tiles at this time.

**Pull request merged**
