### PR TITLE
feat(events-category-search): Events Category Search Page Layout

### PR DESCRIPTION
**Pull request by monik182**
This solves issue #161

### CODE REVIEW

**Comment by CristinaSolana** [comment]
Some issues to resolve

1. padding of sections pictured below seems a bit smaller than it is on mockup. 
screen shot 2017-09-07 at 4 52 38 pm
screen shot 2017-09-07 at 4 52 47 pm

2. Event title font size seems to be off and is using a <p>. Use instead of an <h2> tag for event titles
screen shot 2017-09-07 at 4 53 21 pm
screen shot 2017-09-07 at 4 54 15 pm

**Comment by cristianPerez** [comment]
@monik182 you have a few conflicts in this branch, places solve it.

**Comment by cristianPerez** [comment]
Moni we have some problems in both layouts, events and events/categories.

1) Datepicker.
2) Horizontal Scroll.

screen shot 2017-09-08 at 5 11 33 pm

screen shot 2017-09-08 at 5 12 40 pm

screen shot 2017-09-08 at 5 14 17 pm

**Comment by cristianPerez** [comment]
@monik182 please ensure to make test in screen size mobile and web, before create A PR, or before send changes. because we are solving problems but at the same time we are creating another bugs.

The last mistake in both templates.
http://localhost:1337/events/categories
http://localhost:1337/events/

screen shot 2017-09-08 at 9 22 14 pm

**Pull request merged**
