### PR TITLE
PR for Checkout Tax Page

### PR DESCRIPTION
**Pull request by zetogk**
Template for Checkout Tax Page with CSS styles for desktop and mobile version.

### CODE REVIEW

**Comment by CristinaSolana** [comment]
@zetogk Looks good so far, just needs a few fixes.

1. In "Your Order Summary" padding is incorrect, text is too close to top and bottom borders.
screen shot 2017-08-26 at 10 34 22 am

2. On Card Information, layout needs to be different. Currently you are using:
```
.layout-main-content-tax-page .info-section .content.card-info-content .card-payment-method:nth-child(2) {
    margin-left: 4.45%;
    margin-right: 4.45%;
}
```
this assumes that there will always be 3 and not more than 3 items, but this is dynamic and could be any number of callouts. If there were more callouts than 3, the grid items will be incorrectly aligned as seen below. This section should be layed out using Foundations grid.
screen shot 2017-08-26 at 10 43 15 am

3. On mobile breadcrumbs, do not look as expected. There are some spacing issues and rather than using a >, use an font awesome chevron-right icon.
screen shot 2017-08-26 at 10 32 38 am

**Comment by CristinaSolana** [comment]
A few more changes:

1. text incorrect 
screen shot 2017-08-31 at 2 10 13 pm
screen shot 2017-08-31 at 2 10 09 pm

2. padding for items incorrect
screen shot 2017-08-31 at 2 09 21 pm
screen shot 2017-08-31 at 2 09 27 pm

3. Please put this on one line (not your fault, just an improvement)
screen shot 2017-08-31 at 2 08 46 pm

**Comment by CristinaSolana** [comment]
I merged master in so please pull...

**Comment by zetogk** [comment]
@CristinaSolana   The changes have been done

**Comment by CristinaSolana** [comment]
@zetogk additional changes:

1. space between "edit" icon and link, you can probably just add class margin-left-sm to the icons.
screen shot 2017-09-01 at 8 10 09 am

2. "Points Applied to Your Order" section layout on mobile doesn't look as expected
screen shot 2017-09-01 at 8 13 11 am
screen shot 2017-09-01 at 8 12 37 am

3. On large screen the container that holds the "Your Order Summary" should be large-4 and the container beside it should be large-8
screen shot 2017-09-01 at 8 22 48 am

**Pull request merged**
