### PR TITLE
Feat/checkout step shipping

### PR DESCRIPTION
**Pull request by itsDiwaker**
@CristinaSolana,

Please review and let me know your feedback. For now I have left few console logs for debugging purposes. 

Once we complete the save address to customer profile, I'll do a code clean up. 

There's a mock checkout object that I have used to hide other checkout steps like points applied. That's for now is hard-coded.

### CODE REVIEW

**Comment by itsDiwaker** [comment]
**Notes about the pull request:**

- HTML arrangement in `checkout/shipping.liquid` has been changed.
- `global.scss` has missing class that was lost not sure how. It's for ajax activity loader.
- Background overlay color has been chaged in `_base.scss`

**Comment by CristinaSolana** [comment]
@itsDiwaker We'll go over this flow end to end tomorrow. It should help to take a look at it from the end goal backwards to deconstruct. :)

**Comment by CristinaSolana** [comment]
@itsDiwaker I removed the activity loader overlay for now because it was a bit of overkill for smaller stuff like adding an item to cart. We will need to make it optional. Let's plan this together tomorrow as well.

**Comment by CristinaSolana** [comment]
@monik182 Two issues I noticed:
1. When shipping address is saved it should not show form anymore, should show the address with the edit link. When edit link is clicked then form can be shown again with the current address info
2. When I enter all points, the point value stays at 0. I should be able to pay in 100% points. If I have 100% of points entered then do not show the cc form. Only show if less than the total points is entered.

**Pull request merged**
